export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const PRODUCT_LOADING = 'PRODUCT_LOADING';

export const HANDLE_TOKEN = 'HANDLE_TOKEN';
// export const GET_CURRENT_PROFILE = 'GET_CURRENT_PROFILE';

// export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
// export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
// export const GET_PROFILES = 'GET_PROFILES';
