export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_PRODUCT = 'GET_PRODUCT';
export const PRODUCT_LOADING = 'PRODUCT_LOADING';

export const GET_ALL_SKUS = 'GET_ALL_SKUS';
export const GET_SKU = 'GET_SKU';
export const SKU_LOADING = 'SKU_LOADING';

export const HANDLE_TOKEN = 'HANDLE_TOKEN';

export const GET_ERRORS = 'GET_ERRORS';
export const SET_AUTH_USER = 'SET_AUTH_USER';

export const TOGGLE_CART_OPEN = 'TOGGLE_CART_OPEN';
export const ADD_TO_CART = 'ADD_TO_CART';
// export const FETCH_CART = 'FETCH_CART';
export const SET_CART = 'SET_CART';
export const RESET_CART = 'RESET_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const UPDATE_CART = 'UPDATE_CART'

export const TOGGLE_MODAL_OPEN = 'TOGGLE_MODAL_OPEN';

export const ADD_SHIPPING_ADDRESS= 'ADD_SHIPPING_ADDRESS';
export const SET_SHIPPING_ADDRESS_OPTIONS= 'SET_SHIPPING_ADDRESS_OPTIONS';
export const SET_SELECTED_SHIPPING_ADDRESS= 'SET_SELECTED_SHIPPING_ADDRESS';
export const EDIT_SHIPPING_ADDRESS= 'EDIT_SHIPPING_ADDRESS';
export const SET_BILLING_INFO= 'SET_BILLING_INFO';
export const SET_CHECKOUT_EMAIL= 'SET_CHECKOUT_EMAIL';
export const SET_NEWSLETTER= 'SET_NEWSLETTER';

export const SET_USER = 'SET_USER';
export const RESET_USER = 'RESET_USER';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE'


